export {
  CHAR_COLORS,
  EVENT_TYPES,
  POWER_TIERS,
  DIFFICULTY,
  ARC_STAGES,
  COND_TYPES,
  EQUIP_SLOTS,
  TECH_TYPES,
  MON_TIERS,
  NAT_TYPES,
  RARITY,
  EQUIP_ACCESS,
  NATION_CONNECTION_TYPES,
} from "./constants";

export const uid = () => Math.random().toString(36).slice(2, 8);

export const mkChar = (n: string, color: string) => ({
  id: Math.random().toString(36).slice(2, 8),
  name: n,
  statusTimeline: [],
  color,
  role: "",
  archetype: "",
  coreWound: "",
  coreFear: "",
  coreDesire: "",
  philosophy: "",
  secrets: "",
  arcStart: "",
  arcType: "",
  arcLie: "",
  arcTruth: "",
  arcBreakingPoint: "",
  arcFromEventId: "",
  arcToEventId: "",
  arcEnd: "",
  traumas: [],
  relationships: [],
  branch: [],
  attributes: {},
  conditions: [],
  skills: [],
  equipment: [],
  achievements: [],
  losses: [],
});

import type { Event, EventType, StatusEntry, Condition } from "./types";

export const mkStatusEntry = (): StatusEntry => ({
  id: Math.random().toString(36).slice(2, 8),
  eventId: "",
  startDate: "",
  endDate: "",
  power: "",
  arcStage: "",
  role: "",
  archetype: "",
  emotionalState: "",
  physicalState: "",
  note: "",
});

export const mkSceneCard = () => ({
  id: uid(),
  title: "",
  pov: "",
  goal: "",
  conflict: "",
  outcome: "",
});

export const mkEvent = (): Event => ({
  id: uid(),
  time: 1,
  title: "Untitled event",
  type: "Story" as EventType,
  chapters: [],
  startDate: "",
  endDate: "",
  description: "",
  consequence: "",
  setting: "",
  characters: [],
});
export const mkBranch = () => ({
  id: uid(),
  time: 1,
  title: "",
  type: "Story",
  description: "",
  impact: "",
  crossings: [],
});
export const mkTrauma = () => ({
  id: uid(),
  title: "",
  when: "",
  description: "",
  trigger: "",
  manifestation: "",
});
export const mkRelTimelineEntry = () => ({
  id: uid(),
  time: 1,
  dynamic: "",
});

export const mkRel = () => ({
  id: uid(),
  withId: "",
  feel: "",
  timeline: [],
});
export const mkCond = (): Condition => ({
  id: uid(),
  type: "Physical",
  name: "",
  atTime: "",
  atEventId: "",
  why: "",
  description: "",
  effects: "",
  isActive: true,
});
export const mkSkill = () => ({
  id: uid(),
  name: "",
  atTime: "",
  atEventId: "",
  howGained: "",
  source: "",
  appearance: "",
  attitude: "",
  stats: "",
  cost: "",
  costDescription: "",
  uses: "∞",
  cooldown: "",
  upside: "",
  downside: "",
  requirement: "",
  notes: "",
});
export const mkEquip = () => ({
  id: uid(),
  slot: "Weapon",
  name: "",
  atTime: "",
  atEventId: "",
  stats: "",
  curses: "",
  unbindCondition: "",
  uses: "∞",
  creator: "",
  createdWhy: "",
  ingredients: "",
  lore: "",
  accessState: "Equipped",
  accessNote: "",
});
export const mkAchieve = () => ({
  id: uid(),
  title: "",
  atTime: "",
  atEventId: "",
  description: "",
  gained: "",
});
export const mkLoss = () => ({
  id: uid(),
  title: "",
  atTime: "",
  atEventId: "",
  description: "",
});

export const mkNationConnection = () => ({
  id: uid(),
  withNation: "",
  relation: "Alliance",
  since: "",
  until: "",
  notes: "",
});

export const mkNation = () => ({
  id: uid(),
  name: "",
  type: "Kingdom",
  capital: "",
  ruler: "",
  population: "",
  geography: "",
  culture: "",
  military: "",
  economy: "",
  periodActive: "",
  connections: [],
  allianceLogic: "",
  secrets: "",
  lore: "",
});
export const mkMonster = () => ({
  id: uid(),
  name: "",
  tier: "Minion",
  habitat: "",
  appearance: "",
  abilities: "",
  weaknesses: "",
  drops: "",
  lore: "",
  behavior: "",
  firstSeen: "",
});
export const mkTechnique = () => ({
  id: uid(),
  name: "",
  type: "Blacksmithing",
  origin: "",
  creator: "",
  era: "",
  description: "",
  effect: "",
  requirement: "",
  cost: "",
  secret: "",
  lore: "",
});
export const mkIngredient = () => ({
  id: uid(),
  name: "",
  rarity: "Uncommon",
  location: "",
  appearance: "",
  properties: "",
  uses: "",
  danger: "",
  lore: "",
});
export const mkTreasure = () => ({
  id: uid(),
  name: "",
  rarity: "Rare",
  location: "",
  description: "",
  stats: "",
  curses: "",
  unbindCondition: "",
  creator: "",
  history: "",
  ingredients: "",
});

// ── Styles using CSS variables ─────────────────────────────────────────────
const S: Record<
  string,
  React.CSSProperties | Record<string, React.CSSProperties>
> = {
  app: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    fontFamily: "'Georgia',serif",
    background: "var(--bg-app)",
    color: "var(--text-primary)",
    fontSize: 14,
  },
  row: { display: "flex", flex: 1, overflow: "hidden" },
  top: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 28px",
    height: 48,
    borderBottom: "1px solid var(--border)",
    flexShrink: 0,
    background: "var(--bg-top)",
  },
  logo: {
    fontSize: 13,
    letterSpacing: 4,
    textTransform: "uppercase",
    color: "var(--text-logo)",
  },
  side: {
    width: 224,
    borderRight: "1px solid var(--border)",
    overflowY: "auto",
    padding: "20px 0",
    flexShrink: 0,
    background: "var(--bg-side)",
  },
  main: {
    flex: 1,
    background: "var(--bg-main)",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  h2: {
    fontSize: 13,
    letterSpacing: 3,
    textTransform: "uppercase",
    color: "var(--text-secondary)",
    margin: "0 0 14px",
    fontWeight: 400,
  },
  dim: { color: "var(--text-dim)", fontSize: 12 },
  label: {
    display: "block",
    fontSize: 12,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: "var(--text-secondary)",
    marginBottom: 4,
  },
  select: {
    width: "100%",
    fontSize: 13,
    padding: "4px 0",
    border: "none",
    outline: "none",
    background: "var(--select-bg)",
    color: "var(--select-color)",
  },
  pill: {
    fontSize: 12,
    padding: "4px 10px",
    borderRadius: 4,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-primary)",
    cursor: "pointer",
  },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0 32px" },
  grid3: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "0 24px" },
  grid4: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr 1fr",
    gap: "0 20px",
  },
  input: {
    fontSize: 14,
    padding: "4px 0",
    border: "none",
    outline: "none",
    background: "var(--input-bg)",
    color: "var(--input-color)",
    width: "100%",
  },
  ghost: {
    background: "transparent",
    border: "none",
    outline: "none",
    fontSize: 14,
    cursor: "pointer",
    padding: "2px 0",
    whiteSpace: "nowrap",
    color: "var(--text-secondary)",
  },
  textarea: {
    fontFamily: "'Georgia',serif",
    fontSize: 14,
    padding: "8px 10px",
    border: "1px solid var(--border-field)",
    borderRadius: 4,
    outline: "none",
    width: "100%",
    background: "var(--input-bg)",
    color: "var(--input-color)",
    resize: "vertical",
  },
  rule: {
    border: "none",
    borderTop: "1px solid var(--border)",
    margin: "20px 0",
  },
};

export { S };
